import { GillSans } from "@/app/assets/fonts";
import "@/app/styles/globals.css";
import { AppProvider } from "@/app/context/AppContext";

export const metadata = {
  title: "Taracon Store",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${GillSans.className} antialiased`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
