import { GillSans } from "@/app/assets/fonts";
import "@/app/styles/globals.css";


export const metadata = {
  title: "Taracon Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${GillSans.className} antialiased`}>{children}</body>
    </html>
  );
}
